name: Demo Matrix


on: 
  pull_request:
    types: [opened, reopened]
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
#      - run:  pip install poetry
      - name: Poetry Install
        uses: knowsuchagency/poetry-install@v2
        with:
          create-virtualenv: true
#      - run: poetry install
      - name: run tests
        run: poetry run pytest --verbose --junit-xml=./log/junit.xml --cov-branch --cov=src --cov-report xml
      - name: Archive code coverage results
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ runner.os == 'Linux' }}
        with:
          files: ./log/*.xml

